export default function CourtGraphic() {
  return (
    <svg
      viewBox="0 0 420 220"
      className="mt-10 w-full max-w-md text-accent/70"
      aria-hidden="true"
    >
      <rect
        x="8"
        y="8"
        width="404"
        height="204"
        rx="16"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="8"
        y="70"
        width="110"
        height="80"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="302"
        y="70"
        width="110"
        height="80"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        x1="210"
        y1="8"
        x2="210"
        y2="212"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        cx="210"
        cy="110"
        r="28"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
}
