/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminAuthenticatedRouteRouteImport } from './routes/super-admin/_authenticated/route'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin/login'
import { Route as SuperAdminAuthenticatedDashboardRouteImport } from './routes/super-admin/_authenticated/dashboard'
import { Route as SuperAdminAuthenticatedManageUsersRouteImport } from './routes/super-admin/_authenticated/manage-users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAuthenticatedRouteRoute =
  SuperAdminAuthenticatedRouteRouteImport.update({
    id: '/super-admin/_authenticated',
    path: '/super-admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAuthenticatedDashboardRoute =
  SuperAdminAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => SuperAdminAuthenticatedRouteRoute,
  } as any)
const SuperAdminAuthenticatedManageUsersRoute =
  SuperAdminAuthenticatedManageUsersRouteImport.update({
    id: '/manage-users',
    path: '/manage-users',
    getParentRoute: () => SuperAdminAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminAuthenticatedRouteRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/dashboard': typeof SuperAdminAuthenticatedDashboardRoute
  '/super-admin/manage-users': typeof SuperAdminAuthenticatedManageUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminAuthenticatedRouteRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/dashboard': typeof SuperAdminAuthenticatedDashboardRoute
  '/super-admin/manage-users': typeof SuperAdminAuthenticatedManageUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/super-admin/_authenticated': typeof SuperAdminAuthenticatedRouteRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/_authenticated/dashboard': typeof SuperAdminAuthenticatedDashboardRoute
  '/super-admin/_authenticated/manage-users': typeof SuperAdminAuthenticatedManageUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/super-admin'
    | '/super-admin/login'
    | '/super-admin/dashboard'
    | '/super-admin/manage-users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/super-admin'
    | '/super-admin/login'
    | '/super-admin/dashboard'
    | '/super-admin/manage-users'
  id:
    | '__root__'
    | '/'
    | '/super-admin/_authenticated'
    | '/super-admin/login'
    | '/super-admin/_authenticated/dashboard'
    | '/super-admin/_authenticated/manage-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperAdminAuthenticatedRouteRoute: typeof SuperAdminAuthenticatedRouteRouteWithChildren
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/_authenticated': {
      id: '/super-admin/_authenticated'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/_authenticated/dashboard': {
      id: '/super-admin/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminAuthenticatedDashboardRouteImport
      parentRoute: typeof SuperAdminAuthenticatedRouteRoute
    }
    '/super-admin/_authenticated/manage-users': {
      id: '/super-admin/_authenticated/manage-users'
      path: '/manage-users'
      fullPath: '/super-admin/manage-users'
      preLoaderRoute: typeof SuperAdminAuthenticatedManageUsersRouteImport
      parentRoute: typeof SuperAdminAuthenticatedRouteRoute
    }
  }
}

interface SuperAdminAuthenticatedRouteRouteChildren {
  SuperAdminAuthenticatedDashboardRoute: typeof SuperAdminAuthenticatedDashboardRoute
  SuperAdminAuthenticatedManageUsersRoute: typeof SuperAdminAuthenticatedManageUsersRoute
}

const SuperAdminAuthenticatedRouteRouteChildren: SuperAdminAuthenticatedRouteRouteChildren =
  {
    SuperAdminAuthenticatedDashboardRoute:
      SuperAdminAuthenticatedDashboardRoute,
    SuperAdminAuthenticatedManageUsersRoute:
      SuperAdminAuthenticatedManageUsersRoute,
  }

const SuperAdminAuthenticatedRouteRouteWithChildren =
  SuperAdminAuthenticatedRouteRoute._addFileChildren(
    SuperAdminAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperAdminAuthenticatedRouteRoute:
    SuperAdminAuthenticatedRouteRouteWithChildren,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
