/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin/dashboard'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin/login'
import { Route as SuperAdminManageUsersRouteImport } from './routes/super-admin/manage-users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminManageUsersRoute = SuperAdminManageUsersRouteImport.update({
  id: '/super-admin/manage-users',
  path: '/super-admin/manage-users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/manage-users': typeof SuperAdminManageUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/manage-users': typeof SuperAdminManageUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/manage-users': typeof SuperAdminManageUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/super-admin/dashboard'
    | '/super-admin/login'
    | '/super-admin/manage-users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/super-admin/dashboard'
    | '/super-admin/login'
    | '/super-admin/manage-users'
  id:
    | '__root__'
    | '/'
    | '/super-admin/dashboard'
    | '/super-admin/login'
    | '/super-admin/manage-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  SuperAdminManageUsersRoute: typeof SuperAdminManageUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/manage-users': {
      id: '/super-admin/manage-users'
      path: '/super-admin/manage-users'
      fullPath: '/super-admin/manage-users'
      preLoaderRoute: typeof SuperAdminManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  SuperAdminManageUsersRoute: SuperAdminManageUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
